### ISSUE TITLE
App broken

### ISSUE THREAD

**Issue by buzard49** [yonbergman/project-atlas#1]
App no longer works. Stopped about 3 Apple updates ago. I really like this app. Any plans to update?

**Comment by yonbergman** [comment]
I'll take a look

**Comment by buzard49** [comment]
Thanks. Every one loves this app.  I get the loading screen, and that is
all. None of the images load. We still get the list of sets and cards, but
that is all.

**Comment by yonbergman** [comment]
Submitted version 1.2 to the app store, will update when it's out.
Thanks for bringing this up

**Comment by buzard49** [comment]
Thank you for fixing. I love this app.

**Comment by yonbergman** [comment]
Version 1.2 is out :)

**Comment by buzard49** [comment]
Yay! Thank you.

Sent from my Verizon 4G LTE Smartphone

----- Reply message -----
